theme: jekyll-theme-cayman
title: Open-DIS
description: An open source implementation of the Distributed Interactive Simulation protocol
google_analytics: UA-108076073-1
github:
  repository_url: https://github.com/open-dis
